config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"

  resources :authors
  resources :books
  resources :comments
end

app/models/another_book.rb
class AnotherBook < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, presence: true, length: { minimum: 1 }

    has_one :wikipedium, dependent: :destroy
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :title, presence: true

  has_many :wikipedics, dependent: :destroy
  has_many :image_urls, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :wikipedics, dependent: :destroy
  has_many :similar_books, dependent: :destroy
  has_many :another_books, through: :similar_books
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags
  has_one :gutenberg, dependent: :destroy
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  self.inheritance_column = nil
  after_create_commit lambda {
    broadcast_prepend_to "comments_book_#{reference_id}",
                         partial: 'comments/comment',
                         locals: { comment: self },
                         target: 'comments'
  }

  after_destroy_commit lambda {
    broadcast_remove_to "comments_book_#{reference_id}"
  }

  after_update_commit lambda {
    broadcast_replace_to "comments_book_#{reference_id}"
  }
end

app/models/gutenberg.rb
class Gutenberg < ApplicationRecord
  belongs_to :book
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :book
end

app/models/image_url.rb
class ImageUrl < ApplicationRecord
  belongs_to :book
end

app/models/similar_book.rb
class SimilarBook < ApplicationRecord
  belongs_to :book
  belongs_to :another_book
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/wikipedic.rb
class Wikipedic < ApplicationRecord
  belongs_to :book
end

app/models/wikipedium.rb
class Wikipedium < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.includes(:wikipedium).find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_data)

    respond_to do |f|
      if @author.save
        f.html { redirect_to books_url, notice: "Author created" }
      else
        f.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @author = Author.includes(:wikipedium).find(params[:id])
  end

  def update
    author = Author.find(params[:id])
    if author.update(author_data)
      if author.wikipedium.update(wikipedium_data)
        render action: show
      end
    end
  end

  private
    def author_data
      params.require(:author).permit(:name, :bio, :gender, :summary, :born, :died)
    end

    def wikipedium_data
      params.require(:author).permit(:url, :found)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @authors = Author.all
    author_ids = helpers.list_of_numbers(params[:name])
    @pagy, @records = pagy(helpers.search(author_ids, params[:min], params[:max]))
  end

  def show
    @book = Book.includes(:author, :gutenberg, :image_urls, :images, :wikipedics, :book_tags, :similar_books).find(params[:id])
    @tags = @book.book_tags.includes(:tag)
    @another_books = @book.similar_books.includes(:another_book)
    @goodread = @book.wikipedics.find_by(source: 'goodreads')
    @wikipedium = @book.wikipedics.find_by(source: 'wikipedia')
    @comments = Comment.where(type: 'Book').where(reference_id: @book.id).order(id: :desc)
  end

  def edit
    @book = Book.includes(:author, :gutenberg, :image_urls, :images, :wikipedics, :book_tags, :similar_books).find(params[:id])
    @goodread = @book.wikipedics.find_by(source: 'goodreads')
    @wikipedium = @book.wikipedics.find_by(source: 'wikipedia')
    @tags = @book.book_tags.includes(:tag)
  end

  def update
    @book = Book.find(params[:id])
    return unless @book.update(book_data)

    redirect_to @book

  end

  private

  def book_data
    params.require(:book).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_data)

    respond_to do |f|
      if @comment.save
        f.turbo_stream
      else
        flash.alert = 'Commenting failed'
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |f|
      f.turbo_stream { render turbo_stream: turbo_stream.remove("comments_book_#{@comment.reference_id}") }
      f.html { redirect_to comment_url, notice: 'Deleted!' }
      f.json { head :no_content }
    end
  end

  private

  def comment_data
    params.permit(:name, :message, :type, :reference_id)
  end
end

app/helpers/application_helper.rb
include Pagy::Frontend

module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
    def list_of_numbers(numbers)
        if numbers.nil?
            return []
        end
        numbers.each do |number|
            result = number =~ /[0-9]/
            if result == nil
                raise Exception.new "Required numeric string"
            end
        end
        return numbers ? numbers.reject(&:empty?).map(&:to_i) : []
    end

    def search(name, min, max)
        min ||= []
        max ||= []
        if name.empty?
            if min.present? and max.empty?
                return Book.includes(:author).where(Book.arel_table[:pages].gt(min.to_i))
            elsif min.empty? and max.present?
                return Book.includes(:author).where(Book.arel_table[:pages].lt(max.to_i))
            elsif min.present? and max.present?
                if max.to_i < min.to_i
                    flash[:alert] = "Maximum number should greater that minimum!"
                    return Book.includes(:author).all
                end
                return Book.includes(:author).where(pages: min.to_i..max.to_i)
            end
        elsif name.present?
            if min.present? and max.empty?
                return Book.includes(:author).where(Book.arel_table[:pages].gt(min.to_i)).where(author: {id: name})
            elsif min.empty? and max.present?
                return Book.includes(:author).where(Book.arel_table[:pages].lt(max.to_i)).where(author: {id: name})
            elsif min.present? and max.present?
                if max.to_i < min.to_i
                    flash[:alert] = "Maximum number should greater that minimum!"
                    return Book.includes(:author).all
                end
                return Book.includes(:author).where(pages: min.to_i..max.to_i).where(author: {id: name})
            end
        end
        Book.includes(:author).all
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authors/_form.html.slim
= form_with(model: @author) do |f|
  .columns
    .column
      .control
        = f.label :name
        = f.text_field :name

    .column
      .control
        = f.submit

app/views/authors/edit.html.slim
.container
    h1.title Author
    h2.subtitle
        | #{@author.name} 
        = link_to author_path(@author)
            i.fa-duotone.fa-eye

    = form_with(model: @author) do |f|
        .field
            = f.label :name, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :name, class: "input is-rounded"
        
        .field
            = f.label :bio, class: "label"
            .field-body
                .field
                    .control
                        = f.text_area :bio, class: "textarea is-rounded", rows: "4"

        .field
            = f.label :gender, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :gender, class: "input is-rounded"

        .field
            = f.label :summary, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_area :summary, class: "textarea", rows: "4"

        .field
            = f.label :born, class: "label"
            .control
                = f.text_field :born, class: "input is-rounded", type: "date", value: "#{@author.born&.to_date}"

        .field
            = f.label :died, class: "label"
            .control
                = f.text_field :died, class: "input is-rounded", type: "date", value: "#{@author.died&.to_date}"

        br
        h2.subtitle Wikipedia
        .field
            = f.label :url
            .control
                = f.text_field :url, class: "input is-rounded", value: "#{@author.wikipedium.url}"

            = f.label :found
            .control
                = f.select(:found, [["True", true], ["False", false]], {selected: @author.wikipedium.found}, {class: "input is-rounded"})
        
        = f.submit "Submit", class: "button"

        = turbo_frame_tag dom_id(@author, "author_name") do
          = f.text_field :name
          = f.submit

app/views/authors/new.html.slim
.container
  = link_to sanitize("&larr; Back to quotes"), authors_path

  .header
    h1 New author

  = turbo_frame_tag "new_author_turbo_frame" do
    = render "form", author: @author

app/views/authors/show.html.slim
= turbo_frame_tag "main_frame"
    .container
        h1.title Author
        h2.subtitle
            | #{@author.name} 
            = link_to edit_author_path(@author)
                i.fa.fa-edit
        
        .field
            label.label Name :
            .field-body
                .control #{@author.name}
        
        .field
            label.label Bio :
            .field-body
                .control #{@author.bio}

        .field
            label.label Gender :
            .field-body
                .control #{@author.gender}

        .field
            label.label Summary :
            .field-body
                .control #{@author.summary}

        .field
            label.label Born :
            .field-body
                .control #{@author.born&.to_date}

        .field
            label.label Died :
            .field-body
                .control #{@author.died&.to_date}

        br/    
        h2.subtitle Wikipedia

        .field
            label.label Url :
            .field-body
                .control #{@author.wikipedium.url}

        .field
            label.label Found :
            .field-body
                .control #{@author.wikipedium.found}

app/views/books/_comment.html.slim
.card
  .card-content
    .content
      h1.has-text-centered Chatbox
      input type="hidden" data-books-target="id" value="#{@book.id}"
      input type="hidden" data-books-target="name" value="#{@book.title}"
      input.input type="text" placeholder="Comment" data-action="keydown.enter->books#send_message" data-books-target="message"

      div.comments-scroll
        = turbo_stream_from "comments_book_#{@book.id}"
        = turbo_frame_tag "comments"
        br
        - @comments.each do |comment|
          = turbo_frame_tag dom_id(comment)
            .card
              .card-content
                p #{comment.name}
                p #{comment.message}
                = button_to "Delete", comment_path(comment), method: :delete
          br

app/views/books/edit.html.slim
.container
    h1.title Books
    h2.subtitle
        | #{@book.title} 
        = link_to book_path(@book)
            i.fa-eye

    = form_with model: @book do |f|
        - book_presenter = BookPresenter.new(@book)
        .field
            = f.label :cover, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :cover, class: "input is-rounded"

        .field
            = f.label :title, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :title, class: "input is-rounded"

        .field
            = f.label :content_name, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :content_name, class: "input is-rounded"
        
        .field
            = f.label :isbn, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :isbn, class: "input is-rounded"

        .field
            = f.label :original_title, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :original_title, class: "input is-rounded"

        .field
            = f.label :year, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :year, class: "input is-rounded", type: "number"

        .field
            = f.label :language_code, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :language_code, class: "input is-rounded"
                    
        .field
            = f.label :category, class: "label"
            .field-body
                .field
                    p.control
                        select.select
                            option[selected='#{@book.category == "Text" ? true : false}'] Text
                            option[selected='#{@book.category == "Sound" ? true : false}'] Sound

        .field
            = f.label :plot, class: "label"
            .field-body
                .field
                    .control
                        = f.text_area :plot, class: "textarea is-rounded", rows: "4"

        .field
            = f.label :copyright, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :copyright, class: "input is-rounded"

        .field
            = f.label :average_rating, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :average_rating, class: "input is-rounded"

        .field
            = f.label :description, class: "label"
            .field-body
                .field
                    .control
                        = f.text_area :description, class: "textarea is-rounded", rows: "4"

        .field
            = f.label :loc_class, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :loc_class, class: "input is-rounded"

        .field
            = f.label :language, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :language, class: "input is-rounded"

        .field
            = f.label :release_date, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :release_date, class: "input is-rounded", type: "date", value: "#{book_presenter.release_date}"

        .field
            = f.label :summary, class: "label"
            .field-body
                .field
                    .control
                        = f.text_area :summary, class: "textarea is-rounded", rows: "4"

        .field
            = f.label :pages, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :pages, class: "input is-rounded", type: "number"

        .field
            = f.label :isbn13, class: "label"
            .field-body
                .field
                    p.control
                        = f.text_field :isbn13, class: "input is-rounded"

        h2.subtitle Goodread


        = turbo_frame_tag dom_id(@book, "title_update") do
          = f.text_field :title
          = f.submit
          = link_to "Cancel", book_path

        = turbo_frame_tag dom_id(@book, "content_update") do
          = f.text_field :content_name
          = link_to "Cancel", book_path


        

app/views/books/index.html.slim
.container data-controller="books"
    = form_with url: "/", method: :get do |form|
        .columns
            .column
                .control
                    select(multiple name="name[]")
                        - @authors.each do |author|
                            option value="#{author.id}" #{author.name}

            .column
                .control
                    input#min type="number" class="input" name="min"
            
            .column
                .control
                    input#max type="number" class="input" name="max"

            .column
                .control
                    = form.submit "Submit", class: "button", onclick: ""

    .column
      .control
        = turbo_frame_tag "new_author_turbo_frame" do
          .header
            h1 Author
            = link_to "New Author", new_author_path, class: "button"

    - flash.each do |type, msg|
        .notification.is-danger
            button.delete
            = msg

    br
    table.table.is-bordered
        thead
            tr
                th Cover
                th Title
                th Author
                th Page Number
                th ISBN
                th Year
                th Rating
                th Relese Date
        tbody
            - @records.each do |record|
                tr
                    td
                        figure.image.is-96x96.image-modal-trigger data-target="image-modal"
                            img#image src="#{record.cover}"
                    td
                      = turbo_frame_tag dom_id(record, "title_index_update") do
                        = link_to "#{record.title}", book_path(record), data: { turbo_frame: "_top" }
                    td
                      = link_to "#{record.author.name}", author_path(record)

                    td
                      = turbo_frame_tag "page_index_#{record.id}"
                        | #{record.pages}
                        = link_to "Edit", edit_book_path(record), class: "button"
                    td #{record.isbn}
                    td #{record.year}
                    td #{record.average_rating}
                    td #{record.release_date&.to_date}
    br
    == render partial: 'pagy/nav', locals: {pagy: @pagy}

.modal#image-modal
    .modal-background
    .modal-content
        p.image.is-4by3
            img src="https://bulma.io/images/placeholders/1280x960.png" alt="" id="image-target"
    button.modal-close.is-large aria-label="close"
= javascript_pack_tag 'index'

javascript:
    document.addEventListener('DOMContentLoaded', () => {
        // Functions to open and close a modal
        function openModal($el) {
            $el.classList.add('is-active');
        }

        function closeModal($el) {
            $el.classList.remove('is-active');
        }

        function closeAllModals() {
            (document.querySelectorAll('.modal') || []).forEach(($modal) => {
                closeModal($modal);
            });
        }

        // Add a click event on buttons to open a specific modal
        (document.querySelectorAll('.image-modal-trigger') || []).forEach(($trigger) => {
            const modal = $trigger.dataset.target;
            const $target = document.getElementById(modal);

            $trigger.addEventListener('click', () => {
                openModal($target);
            });
        });

        // Add a click event on various child elements to close the parent modal
        (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button') || []).forEach(($close) => {
            const $target = $close.closest('.modal');

            $close.addEventListener('click', () => {
                closeModal($target);
            });
        });

        // Add a keyboard event to close all modals
        document.addEventListener('keydown', (event) => {
            const e = event || window.event;

            if (e.keyCode === 27) { // Escape key
                closeAllModals();
            }
        });
    });

app/views/books/show.html.slim
= turbo_frame_tag "main_frame"
    .container data-controller="books"
        h1.title Book
        h2.subtitle
            | #{@book.title} 
            = link_to edit_book_path(@book)
                i.fa.fa-edit

        .columns
          .column.is-one-third
            div
              figure.image.is-128x128
                img src="#{@book.cover}"

            .field
              label.label Title
              = form_with model: @book, data: { turbo_frame: dom_id(@book, "title_update") } do |f|
                = turbo_frame_tag dom_id(@book, "title_update")
                  .field-body
                    = link_to @book.title, edit_book_path(@book)

            .field
              label.label Content Name
              = turbo_frame_tag dom_id(@book, "content_update")
                .field-body
                  = link_to @book.content_name, edit_book_path(@book)

            .field
              label.label ISBN
              .field-body
                .control #{@book.isbn}

            .field
              label.label Original Title
              .field-body
                .control #{@book.original_title}

            .field
              label.label Year
              .field-body
                .control #{@book.year}

            .field
                label.label Language Code
                .field-body
                    .control #{@book.language_code}

            .field
              label.label Category
              .field-body
                .control #{@book.category}

          .column
            = render "books/comment"
        
        .field
            label.label Plot
            .field-body
                .control #{@book.plot}
        
        .field
            label.label Copyright
            .field-body
                .control #{@book.copyright}
        
        .field
            label.label Average Rating
            .field-body
                .control #{@book.average_rating}
        
        .field
            label.label Rating Count
            .field-body
                .control #{@book.rating_count}

        .field
            label.label Description
            .field-body
                .control #{@book.description}
        
        .field
            label.label Loc Class
            .field-body
                .control #{@book.loc_class}
        
        .field
            label.label Language
            .field-body
                .control #{@book.language}
        
        .field
            label.label Release Date
            .field-body
                .control #{@book.release_date&.to_date}

        .field
            label.label Summary
            .field-body
                .control #{@book.summary}
        
        .field
            label.label Pages
            .field-body
                .control #{@book.pages}
        
        .field
            label.label ISBN13
            .field-body
                .control #{@book.isbn13}
        
        h2.subtitle Tags

        .card
            .card-content
                .tags
                    - @tags.each do |tag|
                        span.tag.is-rounded #{tag.tag.name}

        br
        h2.subtitle Similar Books

        .card
            .card-content
                .tags
                    - @another_books.each do |another|
                        span.tag.is-rounded #{another.another_book.name}
        
        br
        h2.subtitle Goodread

        .field
            label.label Url
            .field-body
                .control #{@goodread.url}

        .field
            label.label Found
            .field-body
                .control #{@goodread.found}
        
        .field
            label.label Year
            .field-body
                .control #{@goodread.year}
        
        br
        h2.subtitle Wikipedium

        .field
            label.label Url
            .field-body
                .control #{@wikipedium.url}

        .field
            label.label Found
            .field-body
                .control #{@wikipedium.found}
        
        .field
            label.label Year
            .field-body
                .control #{@wikipedium.year}

app/views/comments/_comment.html.slim
= turbo_frame_tag dom_id(comment)
  .card
    .card-content
      p #{comment.name}
      p #{comment.message}
      = button_to "Delete", comment_path(comment), method: :delete
  br

app/views/comments/update.html.slim
= form_with model: @comment do |f|
  = turbo_frame_tag dom_id(@comment)
    = f.text_field :name
    = f.submit
    = link_to "Cancel"